services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  widget:
    build:
      context: ./widget
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend